### ISSUE TITLE
Berries and plants from "compatible mods" grow too quickly.

### ISSUE THREAD

**Issue by gcook725** [Aetherial-Labs/FieldsOfGold#11]
Berry bushes grow too quickly, always saying that their next stage is in less than a day. They progress from nothing to flowering, to ripe in just a few irl minutes. (Tested with JUST FoG, as well as with other mods)

Plants from More Crops and Wildcraft also grow a lot faster than they should. Specifically tested with More Crops and those plants advance 1-3 stages per in game day. (Tested with just FoG and More Crops)

I have not tested anything specifically with Wildcraft, but can confirm that plants regrow faster than the "56 days" advertised on the mod listing page since my server hasn't had that many days pass yet and many herbs have been harvested multiple times. It does still seem slower than Berry Bushes/More Crops, but definitely seems faster than intended.

**Comment by VinterNacht** [comment]
How many days do you have in a month? While in no case should that make crops grow 1-3 stages per game day, it seems to be relevant to the bushes situation. It would seem to be rooted in a math problem, but the math all checks out. The patch for MoreCrops changes their totalGrowthTime as it should. MoreCrops crops are all using the BlockCrop class, just like vanilla crops.

Obviously, this error is happening for some people, but I can't for the life of me see why.  More research is necessary.

**Comment by VinterNacht** [comment]
I believe this has been corrected, it was a weird-ass computer math issue. Let me know your results with rc.5
