### ISSUE TITLE
Yams drop on average 63?

### ISSUE THREAD

**Issue by RogueRaiden** [Aetherial-Labs/FieldsOfGold#14]
More crops patch for yams, near top:

"*-7": [
			{ "type": "item", "code": "potatoes:vegetable-yam", "quantity":  { "avg": **63**, "var": 1 } }

**Comment by VinterNacht** [comment]
LOL That's one hell of a typo!  Will fix!

**Comment by VinterNacht** [comment]
I also noticed they don't drop any seeds at that stage.  Fixed that as well.

**Comment by VinterNacht** [comment]
Fixed on latest release
